import { Suspense } from "react";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './provider';
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className={
            cn(
              "bg-[url('/assets/bg-login.png')] bg-cover",
              "flex flex-col mx-auto",
              "min-h-screen",
              "max-w-[430px]",
            )
          }>
            <Suspense fallback={null}>{children}</Suspense>
          </main>
        </Providers>
      </body>
    </html>
  );
}
